workflows:
  musicplay-android:
    name: MUSIC PLAY Android Build
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.williamsmadaki.musicplay"
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/android
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Android App
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - "williamsmadaki76@gmail.com"
